### ISSUE TITLE
Rancher support for Imported Windows EKS cluster

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#296]
Spike to evaluate the possibility (and effort) to add windows nodes support for imported EKS cluster.

**Comment by mjura** [comment]
I have re-tested once again `Windows` worker nodes support for EKS hosted provider. After cluster provisioning it was needed to enable Windows Support for EKS cluster based on Amazon documentation:
https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support

After it, I used test Windows application deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-server-iis-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: windows-server-iis-test
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: windows-server-iis-test
        tier: backend
        track: stable
    spec:
      containers:
      - name: windows-server-iis-test
        image: mcr.microsoft.com/windows/servercore:1809
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
        command:
        - powershell.exe
        - -command
        - "Add-WindowsFeature Web-Server; Invoke-WebRequest -UseBasicParsing -Uri 'https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe' -OutFile 'C:\\ServiceMonitor.exe'; echo '<html><body><br/><br/><marquee><H1>Hello EKS!!!<H1><marquee></body><html>' > C:\\inetpub\\wwwroot\\default.html; C:\\ServiceMonitor.exe 'w3svc'; "
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
          requests:
            cpu: 128m
            memory: 100Mi
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: windows-server-iis-test
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: windows-server-iis-test
    tier: backend
    track: stable
  sessionAffinity: None
  type: ClusterIP
```
