### ISSUE TITLE
Null values in EKS cluster spec for imported cluster

### ISSUE THREAD

**Issue by cpinjani** [rancher/eks-operator#406]
**Rancher version:**
Rancher version: v2.8.3-rc2
eks-operator: v1.3.1-rc8

**Cluster Type:** Downstream EKS cluster

**Describe the bug:**
Several null values in EKS cluster config spec for imported cluster, hence UI displays incorrect info for subnets, service role. (It shows Rancher created subnet and service role, even its not)
kmsKey, kubernetesVersion, privateAccess, publicAccess, secretsEncryption, securityGroups, serviceRole, subnets, tags, etc.

![image](https://github.com/rancher/eks-operator/assets/73099870/4bb27c10-6beb-464e-8cef-2a7ded727e2f)

**Cluster spec:**
```
eksConfig:
    amazonCredentialSecret: cattle-global-data:cc-xkbjm
    displayName: auto-ekshostcluster-hp-djdof
    ebsCSIDriver: null
    imported: true
    kmsKey: null
    kubernetesVersion: null
    loggingTypes:
      - controllerManager
    nodeGroups:
      - desiredSize: 1
        diskSize: null
        ec2SshKey: null
        gpu: false
        imageId: null
        instanceType: null
        labels:
          alpha.eksctl.io/cluster-name: auto-ekshostcluster-hp-djdof
          alpha.eksctl.io/nodegroup-name: ranchernodes
        launchTemplate:
          id: lt-096147b9b72256038
          name: eksctl-auto-ekshostcluster-hp-djdof-nodegroup-ranchernodes
          version: 1
        maxSize: 1
        minSize: 1
        nodeRole: >-
          arn:aws:iam::<REDACTED>:role/<REDACTED>
        nodegroupName: ranchernodes
        requestSpotInstances: false
        resourceTags: null
        spotInstanceTypes: null
        subnets:
          - <REDACTED>
        tags:
          alpha.eksctl.io/cluster-name: auto-ekshostcluster-hp-djdof
          alpha.eksctl.io/eksctl-version: 0.173.0
          alpha.eksctl.io/nodegroup-name: ranchernodes
          alpha.eksctl.io/nodegroup-type: managed
          aws:cloudformation:logical-id: ManagedNodeGroup
          aws:cloudformation:stack-id: >-
            <REDACTED>
          aws:cloudformation:stack-name: <REDACTED>
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: auto-ekshostcluster-hp-djdof
        userData: null
        version: '1.27'
    privateAccess: null
    publicAccess: null
    publicAccessSources: null
    region: ca-central-1
    secretsEncryption: null
    securityGroups: null
    serviceRole: null
    subnets: null
    tags: null
  enableClusterAlerting: false
  enableClusterMonitoring: false
  enableNetworkPolicy: false
  fleetWorkspaceName: fleet-default
  internal: false
  localClusterAuthEndpoint:
    enabled: false
  windowsPreferedCluster: false
```
